name: Docker Image tools

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
  SPIRE_VERSION: 1.13.2
  REGISTRY: ghcr.io

jobs:
  docker-spire-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "REPOSITORY=${REPOSITORY_NN,,}" >>${GITHUB_ENV}
        env:
          REPOSITORY_NN: '${{ github.repository }}'

      - name: Build and push ubuntu-tools
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile.spire-server
          build-args: |
            SPIRE_VERSION=${{ env.SPIRE_VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/spire-server:${{ env.SPIRE_VERSION }}
